/*
 * Copyright (c) 2025 TamboUI Contributors
 * SPDX-License-Identifier: MIT
 */
package dev.tamboui.tui.bindings;

/**
 * Service interface for registering action handlers from annotated classes.
 * <p>
 * Implementations of this interface are generated by the annotation processor
 * for classes containing {@code @OnAction} annotated methods. They are
 * discovered via {@link java.util.ServiceLoader} and used to wire up
 * action handlers automatically.
 *
 * <pre>{@code
 * // Generated for a class with @OnAction methods:
 * public final class MyApp_ActionHandlerRegistrar
 *         implements ActionHandlerRegistrar<MyApp> {
 *
 *     @Override
 *     public void register(MyApp target, ActionHandler handler) {
 *         handler.on("save", target::save);
 *         handler.on("quit", target::quit);
 *     }
 *
 *     @Override
 *     public Class<MyApp> targetType() {
 *         return MyApp.class;
 *     }
 * }
 * }</pre>
 *
 * @param <T> the type of object containing the annotated methods
 * @see ActionHandler#registerAnnotated(Object)
 */
public interface ActionHandlerRegistrar<T> {

    /**
     * Registers the action handlers from the target object with the handler.
     *
     * @param target  the object containing the annotated methods
     * @param handler the handler to register actions with
     */
    void register(T target, ActionHandler handler);

    /**
     * Returns the target class this registrar handles.
     *
     * @return the target class
     */
    Class<T> targetType();
}
