Source shared_.tape

# Setup
Hide
Type jbang action-handler-demo
Enter
Sleep 2
Show

# Recording
Sleep 2s
Screenshot screenshots/action-handler-demo.svg
Tab
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Right
Right
Up
Up
Sleep 500ms
Up
Left
Left
Sleep 500ms
Left
Left
Sleep 500ms
Tab
Left
Left
Sleep 500ms
Left
Right
Sleep 500ms
Right
Sleep 500ms
Right
Right
Right
Sleep 2500ms
Type "c"
Sleep 2.5s
Type "q"
